services:
    apiservice:
        build:
            dockerfile: SmartDepoAPI/Dockerfile
        ports:
            - "7002:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
    webfront:
        build:
            dockerfile: SmartDepo/Dockerfile
        ports:
            - "7001:8080"
        depends_on:
            - apiservice
        environment:
            - BackendUrl=http://apiservice:8080
            - ASPNETCORE_ENVIRONMENT=Development